site_name: 西瓜hub
theme:
  name: material
  language: zh
  logo: img/logo_xigua_hub.png
  favicon: img/logo_xigua_hub.png
  features:
    - navigation.expand
    - search.highlight
    - search.suggest
  palette:
    primary: black #default  https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/

# 插件
plugins:
  - search:
      lang:
        - en  # 默认的搜索目前还不支持zh，以后解决
        # - jp

# 配置mathjax支持
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - AIOps: 
    - 时序数据:
      - 事件序列分析的一般步骤: aiops/time-series/ts_guidline.md
      - 时序数据特征: aiops/time-series/ts_extracted_features.md
      - 时序常用模型: aiops/time-series/ts_model.md
    - 根因分析(RCA):
      - 论文文献:
        - FluxRank: aiops/rca/paper/fluxrank/fluxrank_paper.md
    - Sentry:
      - Sentry部署: aiops/sentry/sentry_setup.md
    - AIOps实际:
      - AIOps实践分享: aiops/pratice/aiops_pratice_1.md
  - CV: 
    - 开发工具:
      - Linux安装cmake: cv/dev_tools/cmake_install.md
  - AutoML: 
      - nni: nni/nni.md
  - DevOps:
    - Git回滚操作: devops/git_reset.md
  - 杂项:
    - 魔方还原方法:
      - 三角魔方还原: misc/magic_boxes/3th_order.md